### ISSUE TITLE
Getting some high tick counts with growing cuttings

### ISSUE THREAD

**Issue by RogueRaiden** [slightlycolorblind/Wildcraft#14]
A player on my server planted a bunch of cuttings for bushes for their farm and it seems to be costing a few ticks while they grow up. 

20:13:40 [Server Warning] Server overloaded. A tick took 1428ms to complete.
20:13:40 [Server Notification] A tick took 1430.44ms
**gmlewildcraft.BlockEntityWCBerryBush: 1268.44ms**
entity-done-bh-harvestable: 52.58ms
entity-done-bh-emotionstates: 17.92ms
gmleVintagestory.Server.ServerSystemEntitySimulation: 17.03ms
entity-controlledphysics-end: 11.42ms
testspawn game:drifter-deep: 9.42ms
gmleVintagestory.GameContent.BlockEntityFarmland: 9.04ms
ss-tick-Vintagestory.Server.ServerSystemSendChunks: 7.48ms

20:13:48 [Server Warning] Server overloaded. A tick took 1631ms to complete.
20:13:48 [Server Notification] A tick took 1644.65ms
**gmlewildcraft.BlockEntityWCBerryBush: 1591.03ms**
entity-controlledphysics-end: 21.06ms
sleep: 13.06ms
entity-done-bh-repulseagents: 3.66ms
entity-done-bh-timeddespawn: 2.19ms
entity-done-bh-harvestable: 1.4ms
net-read-done: 1.27ms
gmleVintagestory.GameContent.EntityPartitioning: .83ms

20:13:49 [Server Warning] Server overloaded. A tick took 746ms to complete.
20:13:49 [Server Notification] A tick took 746.36ms
**gmlewildcraft.BlockEntityWCBerryBush: 472.01ms**
entity-done-bh-harvestable: 116.53ms
gmleVintagestory.Server.ServerSystemBlockSimulation: 42.05ms
gmleVintagestory.GameContent.BlockEntityFarmland: 26.12ms
gmleVintagestory.GameContent.EntityPartitioning: 16.14ms
entity-controlledphysics-end: 15.7ms
entity-ai-tasks-tick-cont-Vintagestory.GameContent.AiTaskFishOutOfWater: 14.81ms
entity-ai-tasks-tick-start-execVintagestory.GameContent.AiTaskSeekFoodAndEat: 8.44ms

20:15:02 [Server Notification] A tick took 317.04ms
entity-ai-tasks-tick-start-execVintagestory.GameContent.AiTaskSeekEntity: 251.68ms
entity-done-bh-timeddespawn: 37.88ms
sleep: 7.06ms
entity-done-bh-repulseagents: 3.49ms
entity-controlledphysics-end: 2.88ms
gmlePrimitiveSurvival.ModSystem.BETreeHollowGrown: 1.76ms
gmleVintagestory.GameContent.BlockEntityFarmland: 1.73ms
entity-done-bh-health: 1.67ms

**Comment by gabriella-campos-davis** [comment]
Hey, any more info you can give? Was it lag while the cuttings were growing, or when they grew up to berry bushes?

**Comment by RogueRaiden** [comment]
I just saw the high tick rates again. Only thing we could see was blueberry bushes were flowering.
