### ISSUE TITLE
Pressing berries

### ISSUE THREAD

**Issue by Minion0ne** [slightlycolorblind/Wildcraft#17]
pressing berries produces pressed mash that does not allow a second press resulting in no way to get dry mash
the pressed mash will only seem to stack with pressed mash from the same pressing.
clicking on the fruitpress with a stack of mash will put all mash in the press but only return 1 mash.

**Comment by gabriella-campos-davis** [comment]
Yes, pressing berries doesn't quite work correctly at the moment, but should be fixed with the next release
