### ISSUE TITLE
Config file needed

### ISSUE THREAD

**Issue by WickedSchnitzel** [slightlycolorblind/Wildcraft#20]
A config file to tweak things would be nice, e.g. the amount of time poultices need to heal or to disable health regen and use the vanilla behaviour (regen causes lag, or at least it feels like lag). And a config option to disable players taking damage from poisonous plants. such a config should really be a standard if you include such features. Not everybody wants these.

**Comment by gabriella-campos-davis** [comment]
Will be added in the next release
