### ISSUE TITLE
Sedge spawning over water, raspberry bushes broken

### ISSUE THREAD

**Issue by KironaDragryph** [slightlycolorblind/Wildcraft#25]
I've got sedge plants spawning over water in a new world, on 1.17.0-rc.3
![image](https://user-images.githubusercontent.com/31082532/182534470-3761e104-3f6b-4175-a04f-78a099230607.png)

I also had Raspberry bushes spawning over water, as well as having missing textures - 
![image](https://user-images.githubusercontent.com/31082532/182534708-5bd4a37b-fecc-4625-beb2-2ba9fcfd1fce.png)

**Comment by gabriella-campos-davis** [comment]
Try this again with Wildcraft 1.3.0, it should be fixed
