### ISSUE TITLE
Unknown blocks on porting world to 1.17

### ISSUE THREAD

**Issue by avianlights** [slightlycolorblind/Wildcraft#26]
On updating a world generated in 1.16.5 to 1.17.2, previously loaded in-world herbs and berry bushes appear as question mark blocks, including harvested and unharvested plants and berry clippings and bushes at different stages. I am currently using wildcraft v1.4.0 and previously had v1.2.3. I haven't posted an issue before, so I'm not sure what information you need, but I can give you more if you tell me what to look for.
![Screenshot 2022-09-08 155452](https://user-images.githubusercontent.com/113087566/189048878-32a87e05-37e7-4311-98e4-766b47aa3823.png)
![Screenshot 2022-09-08 155530](https://user-images.githubusercontent.com/113087566/189048976-e3c19862-ac8b-44af-9d59-8a8af35aa0cb.png)
![Screenshot 2022-09-08 155606](https://user-images.githubusercontent.com/113087566/189049009-0a249cf1-56d8-4613-b760-5db004bdfe2f.png)
![Screenshot 2022-09-08 155801](https://user-images.githubusercontent.com/113087566/189049039-3a8d5417-8c81-4994-a870-b7326bf67ed8.png)
I had some harvested rosemary in a container that transferred without issues, though. 
![Screenshot 2022-09-08 155257](https://user-images.githubusercontent.com/113087566/189049237-02021f2f-4575-45f4-be37-91abc61fa95b.png)

**Comment by gabriella-campos-davis** [comment]
Ok thank you for this i figured out the problem, will be fixed in the next release
