### ISSUE TITLE
Berry Bushes doens't drop anything when broken

### ISSUE THREAD

**Issue by Fireztonez** [slightlycolorblind/Wildcraft#27]
I have a problem using Wildcraft (v1.4.0 and 1.4.1 is impacted) on VS 1.17.2. When I brake with my hand any berry bushes, nothing drop at all, unless I break the "Ripe" ones, where berries and the bushes drop.

When I remove Wildcraft and do the same in vanilla I can confirm that the bushes always drop.

**Comment by gabriella-campos-davis** [comment]
That's actually an intended feature of Wildcraft, which is why I added clippings to propagate berry bushes.
