### ISSUE TITLE
Failed resolving a blocks item drop or smeltedstack

### ISSUE THREAD

**Issue by WickedSchnitzel** [slightlycolorblind/Wildcraft#28]
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-basil in Block wildcraft:crop-basil-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-bearleek in Block wildcraft:crop-bearleek-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-blackpepper in Block wildcraft:crop-blackpepper-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-celery in Block wildcraft:crop-celery-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-chamomile in Block wildcraft:crop-chamomile-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-cilantro in Block wildcraft:crop-cilantro-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-dill in Block wildcraft:crop-dill-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-dock in Block wildcraft:crop-dock-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-marjoram in Block wildcraft:crop-marjoram-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-marshmallow in Block wildcraft:crop-marshmallow-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-mint in Block wildcraft:crop-mint-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-mustard in Block wildcraft:crop-mustard-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-saffron in Block wildcraft:crop-saffron-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-stingingnettle in Block wildcraft:crop-stingingnettle-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-stjohnswort in Block wildcraft:crop-stjohnswort-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-minerslettuce in Block wildcraft:crop-minerslettuce-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-chicory in Block wildcraft:crop-chicory-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-marigold in Block wildcraft:crop-marigold-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-celandine in Block wildcraft:crop-celandine-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-leek in Block wildcraft:crop-leek-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-yarrow in Block wildcraft:crop-yarrow-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-liquorice in Block wildcraft:crop-liquorice-2
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-basil in Block wildcraft:crop-basil-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-bearleek in Block wildcraft:crop-bearleek-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-blackpepper in Block wildcraft:crop-blackpepper-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-celery in Block wildcraft:crop-celery-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-chamomile in Block wildcraft:crop-chamomile-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-cilantro in Block wildcraft:crop-cilantro-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-dill in Block wildcraft:crop-dill-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-dock in Block wildcraft:crop-dock-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-marjoram in Block wildcraft:crop-marjoram-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-marshmallow in Block wildcraft:crop-marshmallow-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-mint in Block wildcraft:crop-mint-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-mustard in Block wildcraft:crop-mustard-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-saffron in Block wildcraft:crop-saffron-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-stingingnettle in Block wildcraft:crop-stingingnettle-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-stjohnswort in Block wildcraft:crop-stjohnswort-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-minerslettuce in Block wildcraft:crop-minerslettuce-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-chicory in Block wildcraft:crop-chicory-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-marigold in Block wildcraft:crop-marigold-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-celandine in Block wildcraft:crop-celandine-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-leek in Block wildcraft:crop-leek-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-yarrow in Block wildcraft:crop-yarrow-3
9.9.2022 15:12:22 [Warning] Failed resolving a blocks item drop or smeltedstack with code wildcraft:herb-liquorice in Block wildcraft:crop-liquorice-3

**Comment by gabriella-campos-davis** [comment]
This was using wildcraft 1.4.1 right?
