### ISSUE TITLE
Marigold changes to Saltwort

### ISSUE THREAD

**Issue by Grommit68** [slightlycolorblind/Wildcraft#31]
over the last 2 or 3 days I have tried to grow marigold from seeds and each time it turns to saltwort.  It shows as marigold when first planted and at the sprout stage but the final stage turns to saltwort. I am on version 1.4.4

Haven't grown a lot of other seeds but Marigold is the only one I have seen an issue with.

**Comment by gabriella-campos-davis** [comment]
Weird, bug, found the issue, will be fixed in the next release

**Comment by Grommit68** [comment]
Thank you :) 
ps.. love your mod :)
