### ISSUE TITLE
Black berries still called Brambleberry

### ISSUE THREAD

**Issue by Elmfeather7** [slightlycolorblind/Wildcraft#32]
So I noticed that the black berries are still called bramble berries when dried or dehydrated, I took a few screenshots to show what I mean, I've got the lastest version of wildcraft on vs version 1.17.9, I do also have other mods installed including expanded foods.

![2022-11-07_13-43-47](https://user-images.githubusercontent.com/37834855/200216297-1a97cd5d-12f1-437b-944b-4ae6560fee67.png)
![2022-11-07_13-43-49](https://user-images.githubusercontent.com/37834855/200216311-0e5baf98-8889-45e4-bf81-d69761f42f4a.png)

**Comment by gabriella-campos-davis** [comment]
I do believe that dried berries are an expanded-foods invention. I think I mentioned to l33tman that I was updating it, but I can bother him about it again.

**Comment by Elmfeather7** [comment]
Ah okay, didn't realize, thank you for replying.
