### ISSUE TITLE
Black instead of transparent background on hardsedge

### ISSUE THREAD

**Issue by bluelightning32** [slightlycolorblind/Wildcraft#39]
Using wildcraft-v1.6.3.zip with v1.18.0-rc.6
![image](https://user-images.githubusercontent.com/21202621/231947855-bd483ca3-c1db-40f8-ba93-272e015870b6.png)

**Comment by gabriella-campos-davis** [comment]
unfortunately i can't replicate this :( are you playing with many other mods? it could be a texture atlas overflow issue. also it's weird that softsedge doesn't have this problem..

could also be weirdness with a graphics card. not really sure, sorry.

**Comment by bluelightning32** [comment]
It still reproduces with Wildcraft v1.6.4 and VS v1.18.0-rc.8. Only hardsedge and brownsedge are affected.

![image](https://user-images.githubusercontent.com/21202621/232546846-5aaf2ad1-6778-4338-93b2-708442ac3782.png)

 I tried removing all other mods and it didn't help. My OS is Fedora 37 Linux. My graphics card is Sapphire Radeon RX 6600 8GB.

**Comment by bluelightning32** [comment]
The bug also reproduces on Fedora 37 running on the integrated GPU on a Ryzen 5700U laptop CPU.

![image](https://user-images.githubusercontent.com/21202621/232652501-043b9c75-8e35-4921-aa42-655292379490.png)

**Comment by bluelightning32** [comment]
I dual booted the same laptop from the previous comment into Windows. The issue did not reproduce in Windows.

![image](https://user-images.githubusercontent.com/21202621/232661809-30ab4787-d08a-46ee-ad52-7eefeca2fd24.png)

**Comment by bluelightning32** [comment]
The brownsedge and hardsedge png files use Truecolor mode and everything else uses RGBA or Indexed mode.
```
$ for file in *.png; do printf '%-30s %s\n' "$file" "$(identify -verbose $file | grep color_type)"; done
brownsedge_harvested.png           png:IHDR.color_type: 2 (Truecolor)
brownsedge.png                     png:IHDR.color_type: 2 (Truecolor)
green_harvested.png                png:IHDR.color_type: 3 (Indexed)
green.png                          png:IHDR.color_type: 3 (Indexed)
hardsedge_harvested.png            png:IHDR.color_type: 2 (Truecolor)
hardsedge.png                     
![brownsedge_harvested](https://user-images.githubusercontent.com/21202621/232665279-1cc3babd-7421-4412-bb9f-4b0f9f985a26.png)
 png:IHDR.color_type: 2 (Truecolor)
softsedge_harvested.png            png:IHDR.color_type: 6 (RGBA)
softsedge.png                      png:IHDR.color_type: 6 (RGBA)
tule_harvested.png                 png:IHDR.color_type: 3 (Indexed)
tule_medium.png                    png:IHDR.color_type: 3 (Indexed)
tule.png                           png:IHDR.color_type: 6 (RGBA)
tule_small.png                     png:IHDR.color_type: 3 (Indexed)
tule_tufts.png                     png:IHDR.color_type: 6 (RGBA)
waterchestnut_harvested.png        png:IHDR.color_type: 6 (RGBA)
waterchestnut.png                  png:IHDR.color_type: 6 (RGBA)
```

Inside the unpack directory on my Linux computer, I edited the png files. brownsedge has more than 256 colors in it, so I converted it to RGBA. The other files had less than 256 colors, so I converted them to PNG8.
```
[kyle-minecraft@mihoshi sedge]$ convert brownsedge.png PNG32:brownsedge.png
[kyle-minecraft@mihoshi sedge]$ convert brownsedge_harvested.png PNG8:brownsedge_harvested.png 
[kyle-minecraft@mihoshi sedge]$ convert hardsedge.png PNG8:hardsedge.png 
[kyle-minecraft@mihoshi sedge]$ convert hardsedge_harvested.png PNG8:hardsedge_harvested.png 
```

Everything looks correct now.
![image](https://user-images.githubusercontent.com/21202621/232665044-ff6900d0-3a99-4bdb-8255-57bf17350823.png)

Please update the source images with [sedge.zip](https://github.com/gabriella-campos-davis/Wildcraft/files/11257672/sedge.zip).

**Comment by gabriella-campos-davis** [comment]
Hey, thanks so much for doing all the testing on this, the fix will be included in the next update
