### ISSUE TITLE
Burnet not dropping Roots

### ISSUE THREAD

**Issue by Oni-Feralis** [slightlycolorblind/Wildcraft#41]
Every time I harvest burnet(growing) I do not receive the roots from the plant. I tried breaking it with knife, hand, and breaking the soil underneath, which resulted in the plant dropping burnet(growing).
![image](https://user-images.githubusercontent.com/33139809/233851054-16383342-c4fe-4f60-8592-ada92be0b597.png)

**Comment by Oni-Feralis** [comment]
I forgot to mention this was for the version 1.6.4

**Comment by gabriella-campos-davis** [comment]
I'll make sure I look at this again and fix it for the next update, thanks for letting me know

**Comment by gabriella-campos-davis** [comment]
Hi, I can't duplicate this, nothing I've tried with wildcraft 1.6.4 can duplicate this, are you sure you're using the right version?
