### ISSUE TITLE
Perishable roots with no saturation. 

### ISSUE THREAD

**Issue by GoldenstarArtist** [slightlycolorblind/Wildcraft#42]
following roots have no Saturation value: (but they still spoil)
Ginger,  Burnet, Brown Sedge, Sedge

**Comment by gabriella-campos-davis** [comment]
yeah, some roots are meant to not be eaten. At somepoint I will add handbook hints and more info about what you can/can't do with certain roots and herbs. Latest update gave ginger nutrition properties though
