### ISSUE TITLE
Suggestion: Add seed crop Info

### ISSUE THREAD

**Issue by GoldenstarArtist** [slightlycolorblind/Wildcraft#43]
Currently Seeds don't display important information if your choosing to plant them as crops, such as temperature and nutrient requirements. (also this would also help let people know that they are plantable as crops)

![image](https://user-images.githubusercontent.com/15272140/235127217-64bbeefb-358d-403c-9434-8c42dd53cc2f.png)
![image](https://user-images.githubusercontent.com/15272140/235127298-0623cc6e-21fb-4d5b-bd2f-41eb709514d0.png)

**Comment by gabriella-campos-davis** [comment]
good suggestion, will be fixed in the next version.
