### ISSUE TITLE
Scythe

### ISSUE THREAD

**Issue by antoinehu** [slightlycolorblind/Wildcraft#46]
In `WildcraftPlant.OnBlockBroken`, could you change `tool == EnumTool.Knife`  to `(tool == EnumTool.Knife || tool == EnumTool.Sickle || tool == EnumTool.Scythe)` ? I'm using Scythe More, so the scythe works with Wildcraft but it uproots the plant instead of leaving the harvested version, unlike with the knife. I suspect it might come down to this. Though haven't tested.

**Comment by gabriella-campos-davis** [comment]
I'll include this in the next update, seems that's probably what's happening.
