### ISSUE TITLE
herb doubles

### ISSUE THREAD

**Issue by cyraxan** [slightlycolorblind/Wildcraft#5]
some herbs have doubles, for example:
wildcraft:leafygroundvegetable-chamomile-normal
![image](https://user-images.githubusercontent.com/34022944/154033061-078663ad-7c2b-464b-bdea-b97fad63dc68.png)
game:herb-chamomile
![image](https://user-images.githubusercontent.com/34022944/154033362-3d4471e6-9494-41be-a1eb-6a351c1f55fb.png)

**Comment by gabriella-campos-davis** [comment]
Okay, this should be fixed in the next release
