### ISSUE TITLE
Bottles Disappearing

### ISSUE THREAD

**Issue by katjap** [slightlycolorblind/Wildcraft#7]
VS 1.16.4
Expanded Foods 1.5.3-pre.4
OS Windows 10

What Happened:
- Trying to place a 3rd bottle on a shelf results in the bottle disappearing. (not in inventory, not in the world, just deleted)
- Trying to place a bottle in an occupied bottle rack spot also results in bottle disappearing.

What was Expected (one of):
- Bottle would refuse to be placed and stay in inventory
- Swap bottles
- Or better yet bottle would just find an empty space in the rack to fill, like how we can build ladders by just clicking continually on the bottom later block. Once rack is full it would refuse to place a bottle until a space was empty (or do the swapping bottles)

**Comment by gabriella-campos-davis** [comment]
Hi, how does this relate to Wildcraft? This seems like an Expanded Foods problem
