### ISSUE TITLE
Crash when trying to harvest sedge

### ISSUE THREAD

**Issue by genderneutralnoun** [slightlycolorblind/Wildcraft#9]
Title. Possibly for other wildcraft plants as well, haven't tried any others I don't think.
Paste for crash log: https://pastebin.com/bp7meMaX
Yeah, I have too many mods... It's probably an incompatibility, really.

**Comment by gabriella-campos-davis** [comment]
Yeahhh, not sure about that one. I'll see what I can do, but it might be an incompatibility
